name: lockSettingsLockOnJoinConfigurable
in: query
description: Setting to `lockSettingsLockOnJoinConfigurable=true` will allow applying of `lockSettingsLockOnJoin`.
schema:
    type: boolean
    default: false